version: "2.4"
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  girder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: gitlab.kitware.com:4567/core3d/danesfield-app/danesfield-app:${TAG:-latest}
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - girder_assetstore:/home/assetstore
    environment:
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_ADMIN_USER=${GIRDER_ADMIN_USER}
      - GIRDER_ADMIN_PASS=${GIRDER_ADMIN_PASS}

volumes:
  mongo_db:
  girder_assetstore:
