version: "2.4"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $CONDA_PREFIX/var/lib/mongodb:/data/db

  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
