version: "2.4"
services:
  girder:
    volumes:
      - ../server:/home/core3d
    entrypoint: ["/home/provision/girder_entrypoint_dev.sh"]

  worker:
    volumes:
      - ../server:/home/core3d
    entrypoint: ["/home/provision/girder_worker_entrypoint.sh"]
