- hosts: localhost
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: test init
      shell: source $(conda info --base)/etc/profile.d/conda.sh
      args:
        executable: /bin/bash

    - name: Create Conda Environment
      shell: conda env create -f conda_environment.yml

    - name: Activate Conda Environment
      shell: conda activate danesfield

    - name: Launch MongoDB
      shell: |
        mkdir -p $CONDA_PREFIX/var/lib/mongodb
        mongod --fork --syslog --dbpath=$CONDA_PREFIX/var/lib/mongodb
